project_id = "gynpujpwyscgcxhlgsnd"

[functions.confirm-payment]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = false

[functions.stripe-connect-onboard]
verify_jwt = false

[functions.create-daily-room]
verify_jwt = false

[functions.cancel-video-date]
verify_jwt = false

[functions.charge-video-date]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.run-fraud-detection]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-credit-webhook]
verify_jwt = false

[functions.send-message-volley]
verify_jwt = false

