project_id = "gynpujpwyscgcxhlgsnd"

[functions.confirm-payment]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = true

[functions.stripe-connect-onboard]
verify_jwt = true

[functions.create-daily-room]
verify_jwt = true

[functions.cancel-video-date]
verify_jwt = true
